server:
    port: 8081
spring:
    redis: 
        host: ${ReddisHost}
        password: ${ReddisKey}
        ssl: true
        port: ${ReddisPort}
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: ${SQLPassword}
        url: jdbc:mysql://${SQLServer}:${SQLPort}/${SQLDatabase}
        username: ${SQLUsername}
    h2:
        console:
            enabled: false
    jpa:
        hibernate:
            ddl-auto: update
app:    
    checkByDistrictURL: https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id={districtId}&date={dateVal}
    checkByPincodeURL: https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode={pinCode}&date={dateVal}
    dateFormat: dd-MM-yyyy 
    redishost: ${ReddisHost}
    redispassword: ${ReddisKey}
    redisssl: true
    redisport: ${ReddisPort} 
    #cronExp: 0 0/2 * * * ?
    cronExp: 0 * * * * * 
    cacheExpiryInSeconds: 310 
logging:
    level:
        root: ERROR
        com:
            prateek:
                cowinAvailibility: INFO
        
        